- name: my-test-app playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  set_fact:
    mms_api_uri: "{{ mms_base_url }}/api/public/v1.0"
    mms-cluster-hostname-prefix: "mongodb"
    openshift_domain: "default.svc.cluster.local"
    
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: create-group-by-name
    playbook_debug: true
  - role: provision-mongodb
    playbook_debug: true
  - role: get-automation-agent-config
    playbook_debug: true
  - role: add-replica-set
    playbook_debug: true
    when: number_pods_rs is defined
  - role: add-agent-only-pods
    playbook_debug: true
    when: number_pods_aa is defined
 




