- name: my-test-app playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: create-group-by-name
    playbook_debug: true
  - role: provision-my-test-app
    playbook_debug: true
  - role: get-automation-agent-config
    playbook_debug: true
  - role: add-replica-set
    playbook_debug: true



