#
# NOTE: Cluster hostname prefix is defined below and
# general structure is defined below.
# actual cluster names are built in the python
# functions located in library/
# (This is because multiple pods are typically deployed
# per cluster, and each need's it's own unique part
# of the hostname; the '%%pod%%' token is replaced
# with an integer)
#
- name: provision some MongoDB Enterprise contraptions
  strategy: debug
  hosts: localhost
  #gather_facts: false
  connection: local
  pre_tasks:
    - name: setup variables for roles
      set_fact:
        mms_api_uri: "{{ mms_base_url }}/api/public/v1.0"
        cluster_hostname_prefix: "mongodb"
        openshift_domain: "default.svc.cluster.local"
        hostname_token: "%%pod%%"
    - name: build hostname
      set_fact:
        cluster_hostname: >-
          "{{ cluster_hostname_prefix+'-'+mms_project_name+'-'+cluster_name+'-'+hostname_token+'.'+openshift_domain | lower }}"
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: create-group-by-name
    playbook_debug: true
  - role: provision-mongodb
    playbook_debug: true
  - role: get-automation-agent-config
    playbook_debug: true
  - role: add-replica-set
    playbook_debug: true
    when: number_pods_rs is defined
  - role: add-agent-only-pods
    playbook_debug: true
    when: number_pods_aa is defined
 




